// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jstbzgzgzrlllkrkvslg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzdGJ6Z3pnenJsbGxrcmt2c2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NzM0NjQsImV4cCI6MjA2NjE0OTQ2NH0.4VU6wOLLabczc2Kh7HXRrsg2UfifgrfWbm9fOPs6rGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);